"""empty message

Revision ID: eabd26f21dbe
Revises: 
Create Date: 2020-07-23 11:19:20.635056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabd26f21dbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ip', sa.String(length=32), nullable=False),
    sa.Column('first_connect', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
